services:
  web:
    image: ghcr.io/opik/belajar-devops:latest
    container_name: belajar-devops
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

# Kamu nanti cukup tambahkan service lain seperti ini:
#
#  redis:
#    image: redis:7
#    container_name: belajar-redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    networks:
#      - app_network
#
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_PASSWORD=secret
#    restart: always
#    networks:
#      - app_network

networks:
  app_network:
    driver: bridge

