name: Docker Deploy (Cloudflare Tunnel)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Login to GHCR
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} << 'EOF'
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
          EOF

      - name: Deploy via Cloudflare Tunnel
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      
        run: |
          ssh \
            -o ProxyCommand="cloudflared access ssh --hostname $SSH_HOST" \
            -o StrictHostKeyChecking=no \
            $SSH_USER@localhost << 'EOF'

            cd /home/opik/belajar-devops/app
            docker compose pull
            docker compose up -d
            docker image prune -f

            echo "ðŸš€ Deployment success"
          EOF
