name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main
      - fitur-*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:                     
      sha_tag: ${{ steps.meta.outputs.sha_tag }}

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to GHCR (PUSH ONLY)
      - name: Login to GHCR
        if: github.event_name == 'push'      # ⭐ DI SINI
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Prepare Tags
      - name: Extract metadata for tags
        id: meta
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)

          echo "branch_tag=${BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "sha_tag=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT

      # 5. Build & Push Docker Image (PUSH ONLY)
      - name: Build & Push Docker image
        if: github.event_name == 'push'      # ⭐ DI SINI
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/tihsany/belajar-devops:${{ steps.meta.outputs.branch_tag }}
            ghcr.io/tihsany/belajar-devops:${{ steps.meta.outputs.sha_tag }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/tihsany/belajar-devops:latest' || '' }}

      # 6. Show tags (DEBUG)
      - name: Show image tags
        if: github.event_name == 'push'      # ⭐ OPTIONAL
        run: |
          echo "Image pushed:"
          echo "ghcr.io/tihsany/belajar-devops:${{ steps.meta.outputs.branch_tag }}"
          echo "ghcr.io/tihsany/belajar-devops:${{ steps.meta.outputs.sha_tag }}"
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo "ghcr.io/tihsany/belajar-devops:latest"
          fi
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.SERVER_PATH }}
            echo "Updating IMAGE_TAG to ${{ needs.build.outputs.sha_tag }}"
            sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ needs.build.outputs.sha_tag }}/" .env
            docker compose pull
            docker compose up -d
            docker ps
      - name: Debug SHA
          run: |
            echo "SHA from build: ${{ needs.build.outputs.sha_tag }}"

